CXX = c++
ifndef CXXFLAGS
	CXXFLAGS = -Wall -Wextra -pedantic -std=c++11
endif


PROGS = 01-overload \
		02-overload-volume \
		03-overload-sum \
		04-template-sum \
		05-template-equal \
		06-template-multiply \
		07-decltype-sum \
		08-type-traits \
		add-function \
		square

all: $(PROGS)

clean:
	rm -f $(PROGS)


