CXX = c++
CXXFLAGS=-Wall -Wextra -pedantic -std=c++11 -O3

PROGS = 01-pointers-and-references \
		01a-point-to-pointer \
		02-array-copy \
		03-string-pointers \
		04-function-pointers \
		05-function-pointer-passing \
		06-jump-table \
		10-lambda-hello \
		11-passing-lambdas \
		12-cipher \
		13-cipher-char

all: $(PROGS)

clean:
		rm -f $(PROGS)


