CXX = c++
ifndef CXXFLAGS
	CXXFLAGS = -Wall -Wextra -pedantic -std=c++11
endif

PROGS = 01-count-if \
		02-foreach \
		03-copy \
		04-sum \
		05-sum-improved \
		06-accumulate \
		07-divisors-of \
		08-sum-divisible-by \
		09-copy-if \
		10-generate \
		11-inner_product \
		12-sort \
		13-string-trim


all: $(PROGS)

clean:
	rm -f $(PROGS)


