
lab      := lab15b
includes := Animal.h Canine.h Cat.h Dog.h Fish.h Owl.h Pet.h RoboDog.h Robot.h Wolf.h
srcs     := Fish.cpp Cat.cpp Dog.cpp Owl.cpp RoboDog.cpp Wolf.cpp

# common.mk includes step1 (checks $files)
include /var2/lopt/share/cisc187/common.mk

files := $(files) main.cpp

check: step1 


