
lab      := lab12a
includes := Book.h  Date.h  Genre.h 
srcs     := Book.cpp Date.cpp Makefile test_book.cpp test_date.cpp test_hello.cpp

# common.mk includes step1 (checks $files)
include /var2/lopt/share/cisc187/common.mk


check: step1 


