CXX = c++
ifndef CXXFLAGS
	CXXFLAGS = -Wall -Wextra -pedantic -std=c++11
endif

CXXFLAGS+=-I..

PROGS = 01-hello \
		02-struct \
		03-hello-a \
		03-hello-b \
		03-test-hello \
		04-initialization

all: $(PROGS)

clean:
	rm -f $(PROGS)


