#!/usr/bin/expect
set timeout 5
set filename [lindex $argv 0]
set prog [file rootname $filename].exe
log_user 0

source /var2/lopt/share/cisc187/check_common.tcl

send_user "checking file $prog . . . \n"

foreach {v expected} {
  {2 2} 4
  {1 1 2 3 5 8 13 21 34 55 89} 232
  {1 2 3 4 5 6 7 8 9 10} 55
  {4 4 4 4 4 4 4 4 4 4} 40
  {92172 21 8236 01234} 101663
} {
  spawn $prog -a {*}[lrange $v 0 end]
    expect {
      "$expected" {pass "got:  $expected"}
      eof       {abort  "did not add $v" $expected [exec $prog -a {*}[lrange $v 0 end]]}
      timeout    abort
    }
}

# odd tests
foreach {v expected} {
  {1 2 3 4 5} {1 3 5}
  {1 1 2 3 5 8 13 21 34 55 89} {1 1 3 5 13 21 55 89}
  {9 1 2 3 4 5 6 7 8 9 10} {9 1 3 5 7 9}
  {92172 21 8236 01234} {21}
  {2 2} {}
} {
  spawn $prog -o {*}[lrange $v 0 end]
    expect {
      $expected {pass "print odds in $v"}
      eof       {abort  "did not print odds in $v" $expected [exec $prog -o {*}[lrange $v 0 end]]}
      timeout    abort
    }
}

# mean tests
foreach {v expected} {
  {1 2 3 4 5 6} 3.5
  {1 1 2 3 5 8 13 21 34 55 89} 21.0909
  {1 2 3 4 5 6 7 8 9} 5
  {4 4 4 4 4 4 4 4 4 4} 4
  {92172 21 8236 01234} 25415.8
} {
  spawn $prog -m {*}[lrange $v 0 end]
    expect {
      "$expected" {pass "mean of $v"}
      eof       {abort  "did not compute mean of $v" $expected [exec $prog -m {*}[lrange $v 0 end]]}
      timeout    abort
    }
}

# reverse tests
foreach {v expected} {
  {1 2 3 4 5} {5 4 3 2 1}
  {1 1 2 3 5 8 13 21 34 55 89} {89 55 34 21 13 8 5 3 2 1 1}
  {1 2} {2 1}
} {
  spawn $prog -r {*}[lrange $v 0 end]
    expect {
      $expected {pass "reverse $v"}
      eof       {abort  "did not reverse $v" $expected [exec $prog -r {*}[lrange $v 0 end]]}
      timeout    abort
    }
}

