CXX = c++
ifndef CXXFLAGS
	CXXFLAGS = -Wall -Wextra -pedantic -std=c++11
endif
ifndef CFLAGS
	CFLAGS = -Wall -Wextra -pedantic -std=c11
endif

PROGS = 01-pointers-and-references.cpp \
		02-array-copy.c \
		01a-point-to-pointer.cpp \
		03-string-pointers.cpp

all: $(PROGS)

clean:
	rm -f $(PROGS)

