CXX = c++
ifndef CXXFLAGS
	CXXFLAGS = -Wall -Wextra -pedantic -std=c++11
endif


PROGS = 01-default \
		02-copy \
		03-move \
		04-copy-elison \
		05-move-sometimes-copies \
		06-slicing \
		07-exception-slicing \
		chapter.18.3.2 \
		chapter.19.3.7-vector_allocator \
		ex18.4.2 \
		try-this.19.2.3

all: $(PROGS)

clean:
	rm -f $(PROGS)


