CXX = c++
ifndef CXXFLAGS
	CXXFLAGS = -Wall -Wextra -pedantic -std=c++11
endif
CXXFLAGS+=-Wno-unused-variable

PROGS = 01_slicing \
		02_slicing \
		03_slicing \
		04_slicing \
		inheritance-error \
		multiple-inheritance

all: $(PROGS)

clean:
	rm -f $(PROGS)


