
lab      := lab13b
includes := Boat.h RowBoat.h SailBoat.h
srcs     := Boat.cpp RowBoat.cpp SailBoat.cpp

# common.mk includes step1 (checks $files)
include /var2/lopt/share/cisc187/common.mk


check: step1 

