#!/usr/bin/expect
set timeout 5
set filename [lindex $argv 0]
set prog [file rootname $filename].exe
log_user 0

source /var2/lopt/share/cisc187/check_common.tcl

send_user "checking file $prog . . . \n"

spawn $prog
expect {
  "a: 21, b: 11" {pass "default swap"}
  eof        {abort  "did not swap and increment 10,20" "a: 21, b: 11" $expect_out(buffer)}
  timeout    abort
}

foreach {a b expected} {
    2 987 "a: 988, b: 3"
    3 610 "a: 611, b: 4"
    5 377 "a: 378, b: 6"
    8 233 "a: 234, b: 9"
    13 144 "a: 145, b: 14"
    21 89 "a: 90, b: 22"
    34 55 "a: 56, b: 35"
} {
  spawn $prog -a $a -b $b
  expect {
    $expected {pass "swapped $a and $b"}
    eof       {abort  "did not swap and increment $a,$b" $expected [exec $prog -a $a -b $b ]}
    timeout    abort
  }
}

