#!/usr/bin/expect
set timeout 5
set filename [lindex $argv 0]
set prog [file rootname $filename].exe
log_user 0

source /var2/lopt/share/cisc187/check_common.tcl

send_user "checking file $prog . . . \n"

foreach {s expected} {
    "goodbye, cruel world." "Goodbye, cruel world."
    5558675309 "(555) 867-5309"
    "alex stepanov" "Stepanov, A."
    1234567 "1234567"
    "the rain in spain lays mainly on the plain." "The rain in spain lays mainly on the plain."
    7066060842 "(706) 606-0842"
    3474894608 "(347) 489-4608"
    "Twas bryllyg, and Ye slythy toves Did gyre and gymble in ye wabe" "Twas bryllyg, and Ye slythy toves Did gyre and gymble in ye wabe"
    "ɛtsxər dɛikstra" "Dɛikstra, É."
    "That last one was extra credit" "That last one was extra credit"
} {
  send_user "test: $s\n"
  spawn $prog $s
  expect {
    "*$expected*" {pass "got:  $expected"}
    eof       {fail  "did not find: $expected" "" [eval exec $prog $s]}
    timeout    abort
  }
}

