CXX = c++
CXXFLAGS=-Wall -Wextra -pedantic -std=c++11 -O3

PROGS = add \
				binary-print \
				call-stack \
				define \
				passing-parameters \
				simple-parameter \
				sizeof \
				static-variables \
				strings \
				vectors \
				strings_c \
				void-func

all: $(PROGS)

clean:
		rm -f $(PROGS)


