CXX = c++
CXXFLAGS=-Wall -Wextra -pedantic -std=c++11
CFLAGS=-Wall -Wextra -pedantic -std=c11

PROGS = add \
				call-stack \
				define \
				echo \
				passing-parameters \
				simple-parameter \
				static-variables \
				strings \
				vectors \
				strings_c \
				void-func

all: $(PROGS)

clean:
		rm -f $(PROGS)


