CXX = c++
CXXFLAGS=-Wall -Wextra -pedantic -std=c++11 -g -I..
CFLAGS=-Wall -Wextra -pedantic -std=c11 -g

PROGS = add \
		call-stack \
		define \
		echo \
		passing-parameters \
		passing-parameters-test \
		simple-parameter \
		static-variables \
		static-variables-test \
		strings \
		vectors \
		vector-api \
		strings_c \
		void-func

all: $(PROGS)

clean:
		rm -f $(PROGS)
		rm -rf *.dSYM

