CXX = c++
CXXFLAGS=-Wall -Wextra -pedantic -std=c++11 -O3

PROGS = 01-passing-vector \
				02-passing-const-string-and-vector \
				03-set-to-vector-to-C-API

all: $(PROGS)

clean:
		rm -f $(PROGS)


