CXX = c++
CXXFLAGS=-Wall -Wextra -pedantic -std=c++11
CFLAGS=-Wall -Wextra -pedantic -std=c11

PROGS = binary-print \
        float \
        mix-sign \
        overflow \
        sizeof \
        zero

all: $(PROGS)

clean:
		rm -f $(PROGS)


