CXX = c++
ifndef CXXFLAGS
	CXXFLAGS = -Wall -Wextra -pedantic -std=c++11
endif

PROGS = 01-list \
		02-stack \
		03-queue \
		04-stack-init \
		item04-call-empty-not-size-equals-0

all: $(PROGS)

clean:
	rm -f $(PROGS)


