CXX = c++
CXXFLAGS=-Wall -Wextra -pedantic -std=c++11 -O3

PROGS = 01-hello \
				02-struct \
				03-hello-a \
				03-hello-b \
				04-const-correct \
				06-static-variables

all: $(PROGS)

clean:
		rm -f $(PROGS)


