CXX = c++
ifndef CXXFLAGS
	CXXFLAGS = -Wall -Wextra -pedantic -std=c++11
endif

ifndef CXXFLAGS
	CFLAGS=-Wall -Wextra -pedantic -std=c11
endif

PROGS = binary-print \
        float \
        float \
        mix-sign \
        overflow \
        precision \
        sizeof \
        sizes \
        zero

all: $(PROGS)

clean:
		rm -f $(PROGS)


