
lab      := lab5b
includes := math.h student.h
srcs     := main.cpp math.cpp student.cpp

# common.mk includes step1 (checks $files)
include /var2/lopt/share/cisc187/common.mk

files := $(files) class.txt Makefile


check: step1 

