execute pathogen#infect()
syntax on
filetype plugin indent on

set nocompatible

colorscheme slate

" Override the name of the base colorscheme with the name of this custom one
let g:colors_name = "wheat"
hi clear Comment
hi Comment ctermfg=187 

command Hidecomments :hi Comment ctermfg=187 " wheat = 245, 222, 179
command Showcomments :hi Comment ctermfg=4 

function! s:CTest(stepNum)
  execute '!cd ../build; test/step'. a:stepNum
endfunction

command! -nargs=1 Test call s:CTest(<f-args>)
command Steps :!cd ../build; /bin/ls -1 test/step*

:let mapleader = " "

" show an indicator if over 80 columns wide
highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%81v', 100)

" disable arrow keys: pedantic
" noremap <Up>    <Nop>
" noremap <Down>  <Nop>
" noremap <Left>  <Nop>
" noremap <Right> <Nop>


set nobackup
set tabstop=2
set shiftwidth=2
set expandtab

set autowrite            " Write the file if I navigate to a different buffer
set autoread             " Reload the file if it changes outside of vim
set autochdir            " Change directory to the current buffer when opening files.

" Change default comment string for Commentary plugin
" autocmd FileType c,cpp,cs,java setlocal commentstring=//\ %s

set tags=./tags,tags;

" resize split windows by a % of current size
nnoremap <silent> <Leader>= :exe "resize " . (winheight(0) * 3/2)<CR>
nnoremap <silent> <Leader>- :exe "resize " . (winheight(0) * 2/3)<CR>
nnoremap <silent> <Leader>. :exe "vertical resize " . (winwidth(0) * 3/2)<CR>
nnoremap <silent> <Leader>, :exe "vertical resize " . (winwidth(0) * 2/3)<CR>
" move between splits
nnoremap <Leader>h <C-w>h
nnoremap <Leader>j <C-w>j
nnoremap <Leader>k <C-w>k
nnoremap <Leader>l <C-w>l
nnoremap <Leader>= <C-w>=

" netrw preferences
let g:netrw_liststyle = 3          " tree style

let g:netrw_browse_split = 4       " Open selected file in previous window
let g:netrw_preview = 1            " split vertically
let g:netrw_altv = 1               " file with :vsplit to the right of the browser.





