CXX = c++
ifndef CXXFLAGS
	CXXFLAGS = -Wall -Wextra -pedantic -std=c++11
endif

PROGS = 01-class-pointers \
		02-new-delete \
		03-unique_ptr \
		04-calc-ownership-problem \
		05-calc-class \
		06-calc \
		07-calc-vector \
		08-cppreference-unique_ptr


all: $(PROGS)

clean:
	rm -f $(PROGS) demo.txt


