CXX = c++
ifndef CXXFLAGS
	CXXFLAGS = -Wall -Wextra -pedantic -std=c++11
endif
CXXFLAGS+=-Wno-unused-variable

PROGS = 02-overload+ \
		03-postfix-prefix \
		04-const-correct \
		05-function-object \
		06-passing-functors \
		08-static-variables \
		09-static-parameters \
		12-si-units \
		13-bitfields 

all: $(PROGS)

clean:
	rm -f $(PROGS)


