CXX = c++
ifndef CXXFLAGS
	CXXFLAGS = -Wall -Wextra -pedantic -std=c++11
endif

PROGS = 04-function-pointer-calculator \
		05-function-pointer-passing \
		06-jump-table \
		07-sorting \
		10-lambda-hello \
		11-passing-lambdas \
		12-cipher \
		13-cipher-char

all: $(PROGS)

clean:
	rm -f $(PROGS)


