.ds CH Lab #2b
.TL
Lab #2b: Passing parameters and returning values
.so cover-page.ms
.NH
Passing and returning values: 60 minutes \fImaximum\fR
.time_box
.QP
Write a program that takes a \*[c]<string>\*[r] and returns a \*[c]vector<int>\*[r]
containing the number of characters in each \*[c]string\*[r].
Also find the shortest \*[c]string\*[r], the longest \*[c]string\*[r], and the lexicographically first
and last \*[c]string\*[r]s.
.bp
.so reflection.ms
