CXX = c++
ifndef CXXFLAGS
	CXXFLAGS = -Wall -Wextra -pedantic -std=c++11
endif


PROGS = 00-file-io \
		01_open_file \
		02_read_file \
		03_read_lines \
		04_fill_vector \
		05_fill_vector_except \
		06-binary-int \
		07-binary-struct 

all: $(PROGS)

clean:
	rm -f $(PROGS)


