#!/bin/sh

dest=/var2/home/turnitin.d
name=`/usr/bin/whoami`
stamp=`date +%s`

fname=${name}_${1}_${stamp}.zip
shift

zip -r $fname $@ 
cp $fname $dest
chmod 644 $dest/$fname
if [ $? -eq 0 ]; then
    echo "Your assignment was handed in as:    $dest/$fname"
    echo "A copy is also in this directory as: $fname"
    echo "now go and have some fun."
else
    echo "Possible problem turning in your assignment.  Ask for help."
fi 

