CXX = c++
ifndef CXXFLAGS
	CXXFLAGS = -Wall -Wextra -pedantic -std=c++11
endif

PROGS = asciitable \
		change \
		hello \
		hello_c \
		phrase-o-matic \
		printodds \
		random \
		random_clib \
		std11-test \

all: $(PROGS)

clean:
		rm -f $(PROGS)


