CXX = c++
CXXFLAGS=-Wall -Wextra -pedantic -std=c++11 -O3

PROGS = asciitable \
		hello \
		hello_c \
		phrase-o-matic \
		printodds \
		random \
		random_clib \
		std11-test \

all: $(PROGS)

clean:
		rm -f $(PROGS)


