
lab      := lab15a
includes := point.h
srcs     := point.cpp main.cpp

# common.mk includes step1 (checks $files)
include /var2/lopt/share/cisc187/common.mk

files := $(files) Makefile

check: step1

