CXX = c++
ifndef CXXFLAGS
	CXXFLAGS = -Wall -Wextra -pedantic -std=c++11
endif

CXXFLAGS+=-I..

PROGS = chapter.10.7.1-a-problem \
		chapter.10.7.1-better \
		chapter.10.7.1-better2 \
		chapter.10.7.2 \
		side-effects \
		swap-problem

all: $(PROGS)

clean:
		rm -f $(PROGS)

