CXX = c++
ifndef CXXFLAGS
	CXXFLAGS = -Wall -Wextra -pedantic -std=c++11
endif

PROGS = 01-simple-map \
		02-pair \
		03-map-move \
		04-set \
		05-map-set \
		06-multi-map \
		07-multi-set \
		08-unordered-map

all: $(PROGS)

clean:
	rm -f $(PROGS)


